%% Online plotting of figures generated by multich mapping

channel_list = [1,2,3,4,5,6,7,8];
num_channels = size(channel_list,2);

plot_refresh = 5; % seconds

while true
    close all
    for i=1:num_channels
        %Figure Properties
        N = num_channels;
        fullscreen = get(0,'ScreenSize');
        width = 450;
        height = 400;
        delta = 450;
        fig = zeros(N,1);
        ax = zeros(N,1);
        left = 30+350*(mod(i-1,4));
        top = 100;
%         top = 500-100*(i-1);
        if i>4
            top = 500;
        end
        offset= [delta,0,0,0];
        basePos = [ left, top, width, height ];
   
        
        figname = ['Map_',num2str(channel_list(i)),'.fig'];
        g = openfig(figname, 'new','visible');
        set(g, 'Position', basePos)
%         copyobj(get(g,'CurrentAxes'),figure(i));
%         delete(g)
        
    end
    pause(plot_refresh)
    
end


